# Generated by Django 6.0.2 on 2026-02-11 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('birth_place', models.CharField(blank=True, max_length=255, verbose_name='Место рождения')),
                ('job', models.CharField(blank=True, max_length=255, verbose_name='Место работы')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('hobbies', models.TextField(blank=True, verbose_name='Хобби')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('parent', 'Родитель'), ('child', 'Ребенок'), ('sibling', 'Брат/Сестра'), ('spouse', 'Супруг/Супруга'), ('grandparent', 'Бабушка/Дедушка'), ('grandchild', 'Внук/Внучка')], max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('person_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='tree.profile')),
                ('person_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='tree.profile')),
            ],
            options={
                'unique_together': {('person_from', 'person_to', 'relationship_type')},
            },
        ),
    ]
