# Generated by Django 6.0.2 on 2026-02-11 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='relationship',
            options={'verbose_name': 'Связь', 'verbose_name_plural': 'Связи'},
        ),
        migrations.AddField(
            model_name='profile',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичный профиль'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('parent', 'Родитель'), ('child', 'Ребенок'), ('spouse', 'Супруг/Супруга'), ('sibling', 'Брат/Сестра'), ('mother', 'Мать'), ('father', 'Отец'), ('son', 'Сын'), ('daughter', 'Дочь'), ('brother', 'Брат'), ('sister', 'Сестра'), ('husband', 'Муж'), ('wife', 'Жена'), ('grandmother', 'Бабушка'), ('grandfather', 'Дедушка'), ('grandson', 'Внук'), ('granddaughter', 'Внучка')], max_length=20),
        ),
    ]
