# Generated by Django 6.0.2 on 2026-02-12 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_alter_profile_options_alter_relationship_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Анкета', 'verbose_name_plural': 'Анкеты'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_public',
        ),
        migrations.AlterField(
            model_name='relationship',
            name='person_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='tree.profile', verbose_name='Человек'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='person_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='tree.profile', verbose_name='Родственник'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('mother', 'Мать'), ('father', 'Отец'), ('son', 'Сын'), ('daughter', 'Дочь'), ('brother', 'Брат'), ('sister', 'Сестра'), ('husband', 'Муж'), ('wife', 'Жена'), ('grandmother', 'Бабушка'), ('grandfather', 'Дедушка'), ('grandson', 'Внук'), ('granddaughter', 'Внучка'), ('uncle', 'Дядя'), ('aunt', 'Тетя'), ('nephew', 'Племянник'), ('niece', 'Племянница'), ('cousin', 'Двоюродный брат/сестра'), ('mother_in_law', 'Теща/Свекровь'), ('father_in_law', 'Тесть/Свекор'), ('daughter_in_law', 'Невестка'), ('son_in_law', 'Зять')], max_length=20, verbose_name='Тип родства'),
        ),
    ]
