# Generated by Django 6.0.2 on 2026-02-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_alter_profile_options_remove_profile_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('mother', 'Мать'), ('father', 'Отец'), ('son', 'Сын'), ('daughter', 'Дочь')], max_length=20, verbose_name='Тип родства'),
        ),
    ]
