# Generated by Django 6.0.2 on 2026-02-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_alter_relationship_relationship_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='generation',
            field=models.IntegerField(default=0, verbose_name='Поколение'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('mother', 'Мать'), ('father', 'Отец'), ('son', 'Сын'), ('daughter', 'Дочь'), ('husband', 'Муж'), ('wife', 'Жена')], max_length=20, verbose_name='Тип родства'),
        ),
    ]
